# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "develop", "main"]
  pull_request:
    branches: [ "develop", "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Testing back and generating server coverage information
      working-directory: ./server
      run: npm i && npm run coverage
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    - name: Testing front and generating coverage information
      run: npm i && npm run coverage

  coveralls:
    runs-on: ubuntu-latest

    steps:
    - name: Changes lcov info server
      run: echo "$(sed -i 's,SF:,SF:server/,g' ./server/coverage/lcov.info)"
    - name: Changes lcov info
      run: echo "$(sed -i 's,dist/js/webpack:/juicer/,,g' ./coverage/lcov.info)"
    - name: Merging lcov info
      run: cat server/coverage/lcov.info >> coverage/lcov.info
    - name: Evaluates coverage information
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
  
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Creando secreto en el repositorio 

